# -*- coding: utf-8 -*-
"""Portafolio_minv_tang.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oPxHpmMnywY2XWbvNsU0STjRk7Of4Ke3

# Portafolios de inversión: mínima varianza y de tangencia.

# Autor:
Pérez Almazán Marcos


El presente proyecto es un ejercicio de optimización de portafolio de inversión por dos métodos: mínima varianza y de tangencia. Para lo cual se seleccionaron acciones en el periodo va del primer lunes hábil de octubre al último viernes hábil de la primera quincena de noviembre. Las acciones seleccionadas fueron:



1.   Walmart de México
2. CEMEX
3.   Grupo Carso
4.   Arca Continental
5.  Liverpool
6.   PINFRA
7.   ALFA
8.   FEMSA
9.   BAN BAJÍO
10.   BIMBO
11.   Grupo Financiero Inbursa
12.   Grupo México
13.   Chedraui
14.   Kimberly Klark
15.   Grupo Aeroportuario del Pacífico

1. Primero se importan las paqueterías que son necesarias para manejar los datos, graficar y hacer la optimización.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import minimize
import warnings
warnings.filterwarnings('ignore')

"""2. Este apartado es meramente estético.

"""

plt.style.use('seaborn-v0_8-whitegrid')
plt.rcParams['figure.figsize'] = [12, 8]
plt.rcParams['font.size'] = 11
plt.rcParams['font.family'] = 'DejaVu Sans'
plt.rcParams['axes.titlesize'] = 14
plt.rcParams['axes.titleweight'] = 'bold'
plt.rcParams['axes.labelsize'] = 12

"""3. Importamos los datos."""

data = {
    'Fecha': ['15.11.2024', '14.11.2024', '13.11.2024', '12.11.2024', '11.11.2024',
              '08.11.2024', '07.11.2024', '06.11.2024', '05.11.2024', '04.11.2024',
              '01.11.2024', '31.10.2024', '30.10.2024', '29.10.2024', '28.10.2024',
              '25.10.2024', '24.10.2024', '23.10.2024', '22.10.2024', '21.10.2024',
              '18.10.2024', '17.10.2024', '16.10.2024', '15.10.2024', '14.10.2024',
              '11.10.2024', '10.10.2024', '09.10.2024', '08.10.2024', '07.10.2024'],
    'WALMEX': [55.02, 55.04, 56.35, 55.59, 55.28, 56.04, 56.1, 56.05, 55.89, 56.29,
               55.91, 55.02, 55.17, 55.9, 56.98, 57.08, 59.12, 61.54, 60.3, 60.03,
               59.81, 59.54, 58.99, 58.99, 58.78, 59.41, 59.57, 56.37, 57.02, 57.95],
    'CEMEX': [11.2, 10.96, 10.94, 11.28, 11.55, 11.93, 12.09, 11.58, 10.66, 10.47,
              10.57, 10.54, 10.62, 10.59, 11.01, 11.94, 11.95, 11.7, 11.67, 11.78,
              11.95, 11.78, 11.81, 11.72, 11.68, 11.97, 12.01, 11.82, 11.8, 11.43],
    'GCARSO': [117.46, 116.45, 117.35, 119.18, 119.16, 120.27, 123.1, 117.94, 118.33, 118.98,
               122.09, 120.31, 117.96, 118.42, 118.63, 120.09, 119.29, 120.1, 117.95, 121.16,
               121.67, 120.54, 121.16, 122.89, 123.67, 124.11, 124.05, 122.53, 121.09, 123.69],
    'ArcaContinental': [169.92, 167.67, 168.35, 172.09, 170.86, 172.92, 176.06, 173.99, 171.65, 171.53,
                        171.3, 171.31, 172.14, 176.94, 175.49, 174.09, 172.56, 175.71, 175.32, 176.81,
                        180.26, 176.96, 180.15, 180.23, 176.85, 179.32, 179.07, 185.77, 182.54, 184.89],
    'LIVERPOOL': [105.57, 105.95, 104.65, 105.25, 106.29, 106.14, 107.09, 106.24, 104.97, 105.65,
                  104.85, 105.6, 105.43, 105.63, 105.91, 105.86, 106.75, 109.01, 111.89, 113.98,
                  114.09, 112.23, 114.51, 116.34, 117.29, 118.84, 117.05, 117.77, 117.9, 116.17],
    'PINFRA': [176.53, 174.12, 170.99, 173.66, 172.22, 173.25, 176.32, 170.42, 171.65, 174.28,
               174.15, 174.53, 176.26, 180.46, 179.9, 172.77, 172.61, 171.21, 173.54, 174.77,
               177.36, 176.95, 174.35, 174.45, 178.08, 179.56, 178.42, 178.56, 173.69, 178.0],
    'ALFAA': [15.51, 15.51, 15.69, 15.48, 15.59, 15.53, 15.56, 14.53, 13.88, 13.97,
              14.38, 14.5, 14.53, 14.54, 14.24, 14.79, 14.55, 14.55, 14.76, 14.65,
              14.74, 14.3, 14.45, 14.65, 14.96, 15.04, 14.92, 14.54, 14.695, 15.376],
    'FEMSA': [183.79, 186.3, 190.3, 192.07, 195.52, 195.22, 191.81, 194.66, 193.28, 196.3,
              196.15, 194.23, 192.88, 193.85, 196.96, 192.73, 191.47, 193.2, 194.77, 196.32,
              194.75, 190.95, 193.97, 194.64, 190.89, 190.02, 191.51, 191.05, 190.43, 192.04],
    'BBAJIOO': [41.35, 41.9, 41.25, 40.89, 41.98, 42.37, 41.92, 43.87, 44.63, 44.65,
                43.87, 44.48, 43.82, 42.96, 43.84, 43.55, 42.35, 44.43, 45.12, 45.55,
                46.81, 46.14, 43.38, 43.03, 44.57, 44.07, 42.6, 44.14, 44.18, 45.87],
    'BIMBOA': [63.0, 62.49, 62.78, 62.88, 64.97, 66.53, 66.14, 63.56, 62.58, 63.12,
               61.47, 62.16, 61.9, 62.18, 64.86, 63.08, 63.91, 64.26, 64.57, 64.54,
               65.52, 65.41, 65.09, 64.48, 64.26, 65.9, 64.56, 64.64, 65.8, 66.2],
    'GFINBURO': [44.57, 44.21, 43.54, 43.45, 44.02, 44.19, 45.1, 44.53, 44.39, 44.37,
                 43.76, 44.93, 45.3, 45.77, 45.62, 45.68, 45.51, 45.73, 45.35, 45.98,
                 46.6, 46.54, 46.71, 46.23, 46.65, 47.36, 47.51, 46.65, 46.8, 47.33],
    'GMEXICOB': [101.44, 102.37, 102.13, 103.8, 105.47, 106.41, 109.66, 106.52, 108.55, 105.89,
                 104.26, 104.69, 108.09, 105.91, 108.39, 109.9, 109.25, 110.26, 110.72, 112.35,
                 110.28, 108.74, 109.64, 110.12, 110.43, 112.39, 108.84, 107.08, 106.71, 109.63],
    'CHDRAUIB': [127.78, 128.14, 127.71, 127.01, 126.55, 128.33, 129.71, 127.88, 125.11, 126.32,
                 124.04, 126.61, 127.77, 129.52, 129.34, 131.27, 135.14, 136.37, 139.34, 139.37,
                 140.29, 140.1, 140.43, 139.44, 140.29, 142.76, 143.67, 140.07, 142.72, 144.32],
    'KIMBERLYA': [28.3, 28.16, 28.29, 28.46, 28.58, 28.78, 28.76, 28.68, 28.75, 28.77,
                  28.89, 28.73, 28.55, 28.7, 28.42, 28.8, 28.76, 28.57, 28.96, 29.6,
                  30.49, 30.68, 30.38, 30.41, 31.06, 31.61, 30.95, 30.72, 31.51, 32.2],
    'GAPB': [363.64, 364.48, 356.49, 356.1, 355.52, 354.99, 355.07, 346.35, 339.14, 334.11,
             332.09, 340.7, 343.94, 350.98, 351.81, 337.62, 333.53, 334.15, 340.26, 339.83,
             338.18, 336.31, 338.1, 340.41, 333.78, 327.69, 336.48, 330.87, 327.85, 326.05]
}

df = pd.DataFrame(data)
df['Fecha'] = pd.to_datetime(df['Fecha'], format='%d.%m.%Y')
df = df.sort_values('Fecha').reset_index(drop=True)

# Separando precios
precios = df.set_index('Fecha')
acciones = precios.columns.tolist()

print("ANÁLISIS DE PORTAFOLIOS: 15 ACCIONES MEXICANAS")
print(f"Período de análisis: {df['Fecha'].min().date()} a {df['Fecha'].max().date()}")
print(f"Número de observaciones: {len(df)} días")
print(f"Número de activos: {len(acciones)}")
print("\nActivos analizados:")
for i, accion in enumerate(acciones, 1):
    print(f"{i:2d}. {accion}")

"""Estadisticas basicas del portafolio"""

# Rendimientos logarítmicos diarios
rendimientos = np.log(precios / precios.shift(1))
rendimientos = rendimientos.dropna()

# Estadísticas básicas
rendimientos_esperados = rendimientos.mean() * 252  # Anualizados
volatilidades = rendimientos.std() * np.sqrt(252)   # Anualizadas
matriz_covarianza = rendimientos.cov() * 252        # Anualizada

print("\nESTADÍSTICAS DESCRIPTIVAS (ANUALIZADAS)")
stats_df = pd.DataFrame({
    'Retorno Esperado': rendimientos_esperados,
    'Volatilidad': volatilidades,
    'Ratio Retorno/Riesgo': rendimientos_esperados / volatilidades
})
print(stats_df.round(4))
print("\nMatriz de covarianza (primeras 5x5):")
print(matriz_covarianza.iloc[:5, :5].round(6))

"""Funcion que calcula el portafolio de minima varianza"""

def portafolio_minima_varianza(rend_esp, cov_mat):
    """
    Calcula el portafolio de mínima varianza global.

    Parámetros:
    -----------
    rend_esp : array
        Vector de rendimientos esperados
    cov_mat : array
        Matriz de covarianza

    Retorna:
    --------
    array
        Vector de ponderadores óptimos
    """
    n = len(rend_esp)

    # Función objetivo: varianza del portafolio
    def objetivo(w):
        return w @ cov_mat @ w

    # Restricciones: suma de pesos o ponderadores = 1
    restricciones = [{'type': 'eq', 'fun': lambda w: np.sum(w) - 1}]

    # Límites: no se permiten ventas en corto (w ≥ 0)
    limites = [(0, 1) for _ in range(n)]

    # Punto inicial (equiponderado)
    w_inicial = np.ones(n) / n

    # Optimización
    resultado = minimize(objetivo, w_inicial, method='SLSQP',
                         bounds=limites, constraints=restricciones)

    if resultado.success:
        return resultado.x
    else:
        raise ValueError("Optimización fallida")

"""Portafolio de tangencia"""

def portafolio_tangencia(rend_esp, cov_mat, rf):
    """
    Calcula el portafolio de tangencia (máximo Sharpe Ratio).

    Parámetros:
    -----------
    rend_esp : array
        Vector de rendimientos esperados
    cov_mat : array
        Matriz de covarianza
    rf : float
        Tasa libre de riesgo

    Retorna:
    --------
    array
        Vector de ponderadores óptimos
    """
    n = len(rend_esp)

    # Función objetivo: negativo del Sharpe Ratio (para minimizar)
    def objetivo(w):
        retorno = w @ rend_esp
        volatilidad = np.sqrt(w @ cov_mat @ w)
        # Evitar división por cero
        if volatilidad < 1e-10:
            return 1e6
        return -(retorno - rf) / volatilidad

    # Restricciones: suma de ponderadores = 1
    restricciones = [{'type': 'eq', 'fun': lambda w: np.sum(w) - 1}]

    # Límites: no se permiten ventas en corto (w ≥ 0)
    limites = [(0, 1) for _ in range(n)]

    # Punto inicial (equiponderado)
    w_inicial = np.ones(n) / n

    # Optimización
    resultado = minimize(objetivo, w_inicial, method='SLSQP',
                         bounds=limites, constraints=restricciones)

    if resultado.success:
        return resultado.x
    else:
        raise ValueError("Optimización fallida")

def calcular_estadisticas_portafolio(w, rend_esp, cov_mat, rf=0):
    """
    Calcula estadísticas del portafolio.

    Parámetros:
    -----------
    w : array
        Vector de ponderadores
    rend_esp : array
        Vector de rendimientos esperados
    cov_mat : array
        Matriz de covarianza
    rf : float
        Tasa libre de riesgo

    Retorna:
    --------
    dict
        Estadísticas del portafolio
    """
    retorno = w @ rend_esp
    varianza = w @ cov_mat @ w
    volatilidad = np.sqrt(varianza)
    sharpe = (retorno - rf) / volatilidad if volatilidad > 0 else 0

    return {
        'retorno': retorno,
        'volatilidad': volatilidad,
        'varianza': varianza,
        'sharpe': sharpe
    }

def calcular_frontera_eficiente(rend_esp, cov_mat, n_puntos=200):
    """
    Calcula la frontera eficiente de Markowitz.

    Parámetros:
    -----------
    rend_esp : array
        Vector de rendimientos esperados
    cov_mat : array
        Matriz de covarianza
    n_puntos : int
        Número de puntos en la frontera

    Retorna:
    --------
    tuple
        (retornos, volatilidades, ponderadores)
    """
    n = len(rend_esp)
    retorno_min = rend_esp.min()
    retorno_max = rend_esp.max()
    retornos_objetivo = np.linspace(retorno_min, retorno_max, n_puntos)

    frontera_retornos = []
    frontera_volatilidades = []
    frontera_ponderadores = []

    for r_obj in retornos_objetivo:
        # Función objetivo: minimizar varianza
        def objetivo(w):
            return w @ cov_mat @ w

        # Restricciones
        restricciones = [
            {'type': 'eq', 'fun': lambda w: np.sum(w) - 1},
            {'type': 'eq', 'fun': lambda w: w @ rend_esp - r_obj}
        ]

        limites = [(0, 1) for _ in range(n)]
        w_inicial = np.ones(n) / n

        try:
            resultado = minimize(objetivo, w_inicial, method='SLSQP',
                                bounds=limites, constraints=restricciones)

            if resultado.success:
                w_opt = resultado.x
                volatilidad = np.sqrt(resultado.fun)
                frontera_ponderadores.append(w_opt)
                frontera_retornos.append(r_obj)
                frontera_volatilidades.append(volatilidad)
        except:
            continue

    return (np.array(frontera_retornos),
            np.array(frontera_volatilidades),
            np.array(frontera_ponderadores))

"""Calculo de portafolios óptimos"""

# Tasa libre de riesgo (CETES 28 días ~11% anual, ajustado al período)
rf_anual = 0.11
rf_periodo = rf_anual * len(rendimientos) / 252  # Ajuste por el período muestral

print(f"\nTasa libre de riesgo utilizada: {rf_periodo:.4%} (período)")
print(f"Equivalente anualizado: {rf_anual:.2%}")

# Para calcular portafolios óptimos
w_min_var = portafolio_minima_varianza(rendimientos_esperados, matriz_covarianza)
w_tang = portafolio_tangencia(rendimientos_esperados, matriz_covarianza, rf_anual)

# Para calcular estadísticas
estad_min_var = calcular_estadisticas_portafolio(w_min_var, rendimientos_esperados, matriz_covarianza, rf_anual)
estad_tang = calcular_estadisticas_portafolio(w_tang, rendimientos_esperados, matriz_covarianza, rf_anual)

# Pa calcular frontera eficiente
frontera_retornos, frontera_volatilidades, _ = calcular_frontera_eficiente(
    rendimientos_esperados, matriz_covarianza, n_puntos=300
)

print("PORTAFOLIOS ÓPTIMOS")

print("\nA) PORTAFOLIO DE MÍNIMA VARIANZA")

print(f"Retorno esperado: {estad_min_var['retorno']:.4%}")
print(f"Volatilidad: {estad_min_var['volatilidad']:.4%}")
print(f"Sharpe Ratio: {estad_min_var['sharpe']:.4f}")

print("\nB) PORTAFOLIO DE TANGENCIA (MÁXIMO SHARPE RATIO)")

print(f"Retorno esperado: {estad_tang['retorno']:.4%}")
print(f"Volatilidad: {estad_tang['volatilidad']:.4%}")
print(f"Sharpe Ratio: {estad_tang['sharpe']:.4f}")

print("\nC) COMPARACIÓN")
print(f"Diferencia en retorno: {estad_tang['retorno'] - estad_min_var['retorno']:+.4%}")
print(f"Diferencia en volatilidad: {estad_tang['volatilidad'] - estad_min_var['volatilidad']:+.4%}")
print(f"Diferencia en Sharpe: {estad_tang['sharpe'] - estad_min_var['sharpe']:+.4f}")

"""Visualizacion de los portafolios"""

fig, axes = plt.subplots(2, 2, figsize=(15, 12))


# 7.1. GRÁFICO 1: FRONTERA EFICIENTE Y PORTAFOLIOS
ax1 = axes[0, 0]

# Frontera eficiente
ax1.plot(frontera_volatilidades * 100, frontera_retornos * 100,
         'b-', linewidth=1.5, alpha=0.7, label='Frontera Eficiente')

# Portafolios óptimos
ax1.scatter(estad_min_var['volatilidad'] * 100, estad_min_var['retorno'] * 100,
            color='red', s=200, marker='o', edgecolors='black', linewidth=2,
            label='Mínima Varianza', zorder=5)
ax1.scatter(estad_tang['volatilidad'] * 100, estad_tang['retorno'] * 100,
            color='green', s=200, marker='^', edgecolors='black', linewidth=2,
            label='Tangencia', zorder=5)

# Activos individuales
for i, accion in enumerate(acciones):
    ax1.scatter(volatilidades[accion] * 100, rendimientos_esperados[accion] * 100,
               color='gray', s=80, alpha=0.6, zorder=3)
    # Solo etiquetar algunos activos para no saturar
    if i % 3 == 0:  # Cada tercer activo
        ax1.text(volatilidades[accion] * 100 + 0.2,
                rendimientos_esperados[accion] * 100,
                accion, fontsize=8, alpha=0.8)

# Línea del Mercado de Capitales (CML)
vol_max_plot = frontera_volatilidades.max() * 100 * 1.1
x_cml = np.linspace(0, vol_max_plot, 100)
pendiente_cml = (estad_tang['retorno'] * 100 - rf_anual * 100) / (estad_tang['volatilidad'] * 100)
y_cml = rf_anual * 100 + pendiente_cml * x_cml
ax1.plot(x_cml, y_cml, 'r--', linewidth=1.5, alpha=0.7, label='Línea CML')

# Tasa libre de riesgo
ax1.scatter(0, rf_anual * 100, color='purple', s=150, marker='s',
           edgecolors='black', linewidth=2, label=f'Rf = {rf_anual:.1%}', zorder=5)

ax1.set_xlabel('Volatilidad Anualizada (%)', fontsize=12)
ax1.set_ylabel('Retorno Esperado Anualizado (%)', fontsize=12)
ax1.set_title('Frontera Eficiente y Portafolios Óptimos', fontsize=14, fontweight='bold')
ax1.grid(True, alpha=0.3, linestyle='--')
ax1.legend(loc='upper left', fontsize=10)
ax1.set_xlim([0, vol_max_plot])
ax1.set_ylim([rf_anual * 100 - 5, frontera_retornos.max() * 100 + 5])


# 7.2. GRÁFICO 2: DISTRIBUCIÓN DE PONDERADORES - MÍNIMA VARIANZA

ax2 = axes[0, 1]

# Ordenar ponderadores
indices_ordenados = np.argsort(w_min_var)[::-1]
acciones_ordenadas = [acciones[i] for i in indices_ordenados]
pesos_ordenados = w_min_var[indices_ordenados]

# Barras
bars2 = ax2.barh(range(len(acciones_ordenadas)), pesos_ordenados * 100,
                color='lightcoral', edgecolor='darkred', linewidth=1)

ax2.set_yticks(range(len(acciones_ordenadas)))
ax2.set_yticklabels(acciones_ordenadas, fontsize=9)
ax2.set_xlabel('Ponderación (%)', fontsize=12)
ax2.set_title('Portafolio de Mínima Varianza: Distribución', fontsize=14, fontweight='bold')
ax2.grid(True, alpha=0.3, axis='x', linestyle='--')
ax2.invert_yaxis()  # El activo con mayor ponderación arriba

# Etiquetas de porcentaje
for i, bar in enumerate(bars2):
    width = bar.get_width()
    if width > 1:  # Solo etiqueta si es significativo
        ax2.text(width + 0.5, bar.get_y() + bar.get_height()/2,
                f'{width:.1f}%', ha='left', va='center', fontsize=8)

# 7.3. GRÁFICO 3: DISTRIBUCIÓN DE PONDERADORES - TANGENCIA
ax3 = axes[1, 0]

# Ordenar ponderadores
indices_ordenados_t = np.argsort(w_tang)[::-1]
acciones_ordenadas_t = [acciones[i] for i in indices_ordenados_t]
pesos_ordenados_t = w_tang[indices_ordenados_t]

# Barras
bars3 = ax3.barh(range(len(acciones_ordenadas_t)), pesos_ordenados_t * 100,
                color='lightgreen', edgecolor='darkgreen', linewidth=1)

ax3.set_yticks(range(len(acciones_ordenadas_t)))
ax3.set_yticklabels(acciones_ordenadas_t, fontsize=9)
ax3.set_xlabel('Ponderación (%)', fontsize=12)
ax3.set_title('Portafolio de Tangencia: Distribución', fontsize=14, fontweight='bold')
ax3.grid(True, alpha=0.3, axis='x', linestyle='--')
ax3.invert_yaxis()

# Etiquetas de porcentaje
for i, bar in enumerate(bars3):
    width = bar.get_width()
    if width > 1:
        ax3.text(width + 0.5, bar.get_y() + bar.get_height()/2,
                f'{width:.1f}%', ha='left', va='center', fontsize=8)



# 7.4. GRÁFICO 4: COMPARACIÓN DE CARACTERÍSTICAS
ax4 = axes[1, 1]

caracteristicas = ['Retorno', 'Volatilidad', 'Sharpe Ratio']
valores_min_var = [estad_min_var['retorno'] * 100,
                   estad_min_var['volatilidad'] * 100,
                   estad_min_var['sharpe']]
valores_tang = [estad_tang['retorno'] * 100,
                estad_tang['volatilidad'] * 100,
                estad_tang['sharpe']]

x = np.arange(len(caracteristicas))
ancho = 0.35

bars4a = ax4.bar(x - ancho/2, valores_min_var, ancho,
                label='Mínima Varianza', color='lightcoral', edgecolor='darkred')
bars4b = ax4.bar(x + ancho/2, valores_tang, ancho,
                label='Tangencia', color='lightgreen', edgecolor='darkgreen')

ax4.set_xlabel('Característica', fontsize=12)
ax4.set_ylabel('Valor', fontsize=12)
ax4.set_title('Comparación de Portafolios Óptimos', fontsize=14, fontweight='bold')
ax4.set_xticks(x)
ax4.set_xticklabels(caracteristicas)
ax4.legend()
ax4.grid(True, alpha=0.3, axis='y', linestyle='--')

# Añadir etiquetas de valor
def autolabel(bars):
    for bar in bars:
        height = bar.get_height()
        ax4.annotate(f'{height:.2f}',
                    xy=(bar.get_x() + bar.get_width() / 2, height),
                    xytext=(0, 3),  # 3 points vertical offset
                    textcoords="offset points",
                    ha='center', va='bottom', fontsize=8)

autolabel(bars4a)
autolabel(bars4b)

plt.tight_layout()
plt.show()

"""Tangencia"""

fig2, ax5 = plt.subplots(figsize=(10, 7))

# Frontera eficiente con más detalle
ax5.plot(frontera_volatilidades * 100, frontera_retornos * 100,
         'b-', linewidth=1.2, alpha=0.8, label='Frontera Eficiente')

# Puntos individuales de la frontera (cada 10 puntos para no saturar)
puntos_a_mostrar = range(0, len(frontera_volatilidades), 10)
ax5.scatter(frontera_volatilidades[puntos_a_mostrar] * 100,
           frontera_retornos[puntos_a_mostrar] * 100,
           color='blue', s=30, alpha=0.5, label='Portafolios factibles')

# Portafolios óptimos
ax5.scatter(estad_min_var['volatilidad'] * 100, estad_min_var['retorno'] * 100,
            color='red', s=200, marker='o', edgecolors='black', linewidth=2,
            label='Mínima Varianza', zorder=5)
ax5.scatter(estad_tang['volatilidad'] * 100, estad_tang['retorno'] * 100,
            color='green', s=200, marker='^', edgecolors='black', linewidth=2,
            label='Tangencia', zorder=5)

# Línea CML con más detalle
x_cml_detalle = np.linspace(0, estad_tang['volatilidad'] * 100 * 1.5, 100)
y_cml_detalle = rf_anual * 100 + pendiente_cml * x_cml_detalle
ax5.plot(x_cml_detalle, y_cml_detalle, 'r--', linewidth=2, alpha=0.8, label='Línea CML')

# Tasa libre de riesgo
ax5.scatter(0, rf_anual * 100, color='purple', s=180, marker='s',
           edgecolors='black', linewidth=2, zorder=5)
ax5.annotate(f'Rf = {rf_anual:.1%}', xy=(0.5, rf_anual * 100 + 0.5),
             fontsize=10, fontweight='bold')

# Línea vertical y horizontal desde el portafolio de tangencia
ax5.axhline(y=estad_tang['retorno'] * 100, xmax=estad_tang['volatilidad'] * 100 / vol_max_plot,
            color='gray', linestyle=':', alpha=0.5)
ax5.axvline(x=estad_tang['volatilidad'] * 100, ymax=(estad_tang['retorno'] * 100 - rf_anual * 100) /
            (frontera_retornos.max() * 100 - rf_anual * 100),
            color='gray', linestyle=':', alpha=0.5)

# Anotaciones
ax5.annotate('Punto de tangencia',
             xy=(estad_tang['volatilidad'] * 100, estad_tang['retorno'] * 100),
             xytext=(estad_tang['volatilidad'] * 100 + 3, estad_tang['retorno'] * 100 + 2),
             arrowprops=dict(arrowstyle='->', color='green', alpha=0.7),
             fontsize=10, fontweight='bold')

ax5.annotate('Mínima varianza global',
             xy=(estad_min_var['volatilidad'] * 100, estad_min_var['retorno'] * 100),
             xytext=(estad_min_var['volatilidad'] * 100 + 3, estad_min_var['retorno'] * 100 - 2),
             arrowprops=dict(arrowstyle='->', color='red', alpha=0.7),
             fontsize=10, fontweight='bold')

ax5.set_xlabel('Volatilidad Anualizada (%)', fontsize=12)
ax5.set_ylabel('Retorno Esperado Anualizado (%)', fontsize=12)
ax5.set_title('Análisis Detallado: Punto de Tangencia y Frontera Eficiente',
              fontsize=14, fontweight='bold')
ax5.grid(True, alpha=0.3, linestyle='--')
ax5.legend(loc='upper left', fontsize=10)
ax5.set_xlim([0, vol_max_plot])
ax5.set_ylim([rf_anual * 100 - 2, frontera_retornos.max() * 100 + 2])

plt.tight_layout()
plt.show()
